### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by naivefun** [th0th/rancher-redeploy-workload#3]
Post "https://xxx.io/v3/xxxx/workloads/deployment:gapin-stage:gapin-api?action=redeploy": x509: certificate signed by unknown authority

how to work around this ssl?

```yaml
    - run: sudo apt-get install -y ca-certificates
    - run: sudo cp ./rancher.crt /usr/local/share/ca-certificates
    - run: sudo update-ca-certificates
    
    - name: 7. Rancher Deploy
      uses: th0th/rancher-redeploy-workload@v0.9
      env:
        RANCHER_BEARER_TOKEN: xxx
```
